(() => {
//If you want to add more images, add the link name and URL image URL in the array list below.
	const images_list = [
{
    "url": "castro.png",
    "alt": "",
    "name": "castro",
    "link": ""
},
{
    "url": "coachVirtual.png",
    "alt": "",
    "name": "coachVirtual",
    "link": ""
},
{
    "url": "estudioJuridico.png",
    "alt": "",
    "name": "estudioJuridico",
    "link": ""
},
{
    "url": "heisemberg.png",
    "alt": "",
    "name": "image 4",
    "link": ""
},
{
    "url": "improfop.png",
    "alt": "",
    "name": "image 5",
    "link": ""
},
{
    "url": "IronGym.png",
    "alt": "",
    "name": "IronGym",
    "link": ""
},
{
    "url": "masterU.png",
    "alt": "",
    "name": "masterU",
    "link": ""
},
{
    "url": "pipa.png",
    "alt": "",
    "name": "pipa 5",
    "link": ""
},
{
    "url": "Riaus.png",
    "alt": "",
    "name": "Riaus",
    "link": ""
}
	];

    // generated by https://www.html-code-generator.com/html/image-slideshow-generator
	let slider_id = document.querySelector("#carrucel");

	// append all images
	let dots_div = "";
	let images_div = "";
	for (let i = 0; i < images_list.length; i++) {
		// if no link without href="" tag
		let href = (images_list[i].link == "" ? "":' href="'+images_list[i].link+'"');
		images_div += '<a'+href+' class="hcg-slides animated"'+(i === 0 ? ' style="display:flex"':'')+'>'+
						'<img src="./assets/clientes/'+images_list[i].url+'" alt="'+images_list[i].name+'">'+
					 '</a>';
	}
	slider_id.querySelector(".hcg-slider-body").innerHTML = images_div;
	let slide_index = 0;

	const images = slider_id.querySelectorAll(".hcg-slides");
	const showSlides = () => {
		if (slide_index > images.length-1) {
			slide_index = 0;
		}
		if (slide_index < 0) {
			slide_index = images.length-1;
		}
		for (let i = 0; i < images.length; i++) {
			images[i].style.display = "none";
			if (i == slide_index) {
				images[i].style.display = "flex";
			}
		}
	}

	// auto play
	setInterval(() => {
		slide_index++;
		showSlides();
	}, 2000);

})();

